init:
  - git config --global core.autocrlf true

image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: StarshipResupply.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[StarshipResupply.Application.Services.Tests*]* -[StarshipResupply.Domain.Services.Tests*]* -[StarshipResupply.Data.Gateway.Tests*]*" -output:".\StarshipResupply_Coverage.xml" -oldstyle
- codecov -f "StarshipResupply_Coverage.xml" -t $(codecov_token)