image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: StarshipResupply.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:administrator -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[StarshipResupply*Tests*]*" -output:".\StarshipResupply_Coverage.xml" -oldstyle
- Type "StarshipResupply_Coverage.xml"
- codecov -f "StarshipResupply_Coverage.xml"