{
    "codecov": {
        "bot": "codecov-io", 
        "ci": [
            "travis.org"
        ], 
        "disable_default_path_fixes": false, 
        "max_report_age": 24, 
        "notify": {
            "after_n_builds": 2, 
            "wait_for_ci": true
        }, 
        "require_ci_to_pass": true, 
        "strict_yaml_branch": "yaml-config", 
        "token": "175a7ec1-11d0-47f1-bb99-3c55b5517f94"
    }
}